language: python
sudo: false
addons:
  apt:
    packages:
      - requests
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
    # This environment tests the oldest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="2.7"
    # This environment tests the newest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="3.4" 
install: source continuous_integration/install.sh
cache: apt
script: nosetests
